name: Weather Data Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-weather-data-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Navegar a la carpeta Parte3-3
      run: cd Parte3-3

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary requests || echo "Error en la base de datos, continuando con la ejecuci贸n"

    - name: Ejecutar script de obtenci贸n de datos meteorol贸gicos
      run: |
        cd Parte3-3
        python weather_data.py || echo "Error en la base de datos, generando solo el CSV"

    - name: Agregar y subir CSV
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add Parte3-3/weather_data.csv
        git commit -m 'Actualizar archivo CSV de datos meteorol贸gicos'
        git push https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/Jacoroch/PruebaDatos.git HEAD:main
